apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile-config
data:
  MYSQL_DB_HOST: {{ .Values.profile.mysql.host | quote }}
  MYSQL_DB_PORT: {{ .Values.profile.mysql.port | quote }}
  MYSQL_DB_NAME: {{ .Values.profile.mysql.database | quote }}
