apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-profile-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-profile-deployment
  minReplicas: {{ .Values.profile.hpa.minReplicas }}
  maxReplicas: {{ .Values.profile.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.profile.hpa.targetCPUUtilizationPercentage }}
