apiVersion: v1
kind: Secret
metadata:
  name: login-secret
type: Opaque
data:
  mysql-username: {{ .Values.login.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.login.mysql.password | b64enc | quote }}
