{{- if eq .Values.global.environment "gcp" }}
apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  mysql-username: {{ .Values.chat.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.chat.mysql.password | b64enc | quote }}
{{- end }}
