apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
data:
  mysql-username: {{ .Values.profile.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.profile.mysql.password | b64enc | quote }}
