apiVersion: v1
kind: Service
metadata:
  name: spring-profile-service
spec:
  type: {{ .Values.profile.service.type }}
  selector:
    app: spring-profile
  ports:
    - port: {{ .Values.profile.service.port }}
      targetPort: {{ .Values.profile.service.targetPort }}
      protocol: TCP
